version: '3.5'
volumes:
  data:

services:
  db:
    image: postgres:12-alpine
    container_name: db_projcompras
    environment:
      POSTGRES_DB: comprasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./test/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d